name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - PHP ${{ matrix.php }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        php: ['8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer validate
        run: composer validate --strict

      - name: Composer install
        run: composer install

      - name: Codestyle check
        run: vendor/bin/php-cs-fixer fix -v --dry-run

      - name: Static analyze
        run: vendor/bin/psalm

      - name: Tests
        run: vendor/bin/phpunit
